name: Driver publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.KEY_ONE }}

      - name: Copy kindling-falcolib-probe from hosts
        shell: bash
        env:
          HOSTS: ${{ secrets.HOSTS }}
          REMOTE_PROBE_DIR: /tmp/kindling-falcolib-probe
        run: |
          # Add the host key
          echo ${{ secrets.HOST_KEY_ONE }} >> ~/.ssh/known_hosts
          echo ${{ secrets.HOST_KEY_TWO }} >> ~/.ssh/known_hosts

          mkdir -p /tmp/kindling-falcolib-probe
          for HOST in $HOSTS; do
          {
            echo "Copying from $HOST:${REMOTE_PROBE_DIR}"
            scp "$HOST:${REMOTE_PROBE_DIR}/*" /tmp/kindling-falcolib-probe/
          }&
          done
          wait
          echo "Copy successfully"

      - name: Package
        shell: bash
        run: |
          tar -cvzf /tmp/kindling-falcolib-probe.tar.gz -C /tmp kindling-falcolib-probe
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: kindling-falcolib-probe-${{ github.run_id }}
          name: kindling-falcolib-probe ${{ github.run_id }}
          body: |
            Auto-created by Driver publish workflow.
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Commit: ${{ github.sha }}
          files: /tmp/kindling-falcolib-probe.tar.gz
          draft: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
